version: "1.1.3"
services:
  back:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sjhn/gongnomok-backend:1.1.5
    restart: always
    ports:
      - 8080:8080
  front:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sjhn/gongnomok-frontend:1.1.3
    restart: always
    ports:
      - 80:80
      - 443:443
