version: "1.2.0"
services:
  back:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sjhn/gongnomok-backend:prod-1.2.0
    restart: always
    ports:
      - 8080:8080
  front:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sjhn/gongnomok-frontend:prod-1.2.0
    restart: always
    ports:
      - 80:80
      - 443:443
