management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-components: always
  info:
    java:
      enabled: true
    os:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true