spring:
  datasource:
    url: jdbc:mysql://db2.gongnomok.site:3306/gongnomok?serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    username: jh
    password: jh980101^^
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hi
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
    open-in-view: false