services:
  back:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: backend/docker/Dockerfile
    image: sjhn/gongnomok-backend:prod-1.2.3
    restart: always
    ports:
      - 8080:8080