name: Backend CI

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  PATH_CHANGES:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
  
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'

  BACKEND_CI:
    runs-on: ubuntu-latest
    needs: PATH_CHANGES
    if: ${{ needs.PATH_CHANGES.outputs.backend == 'true' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Java
        uses: actions.setup-java@4
        with:
          distribution: 'corretto'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        continue-on-error: true
        id: gradle_test
        run: |
          cd backend
          ./gradlew test
